reactor/reactor

reactor-core/src/main/java/reactor/bus/EventBus.java, reactor-core/src/main/java/reactor/bus/registry/CachingRegistry.java, reactor-core/src/main/java/reactor/bus/registry/Registries.java, reactor-core/src/main/java/reactor/bus/registry/SimpleCachingRegistry.java, reactor-core/src/main/java/reactor/bus/spec/EventRoutingComponentSpec.java, reactor-core/src/main/java/reactor/core/dispatch/processor/spec/ProcessorSpec.java, reactor-core/src/main/java/reactor/fn/timer/SimpleHashWheelTimer.java, reactor-core/src/test/groovy/reactor/bus/RegistrySpec.groovy, reactor-core/src/test/java/reactor/bus/SelectorUnitTests.java, reactor-core/src/test/java/reactor/bus/registry/CachingRegistryTests.java, reactor-groovy/src/main/groovy/reactor/groovy/config/ReactorBuilder.groovy
This change introduces a new Registry implementation that doesn't use the gs-collections library and is intended for use in situations where gs-collections causes problems when creating a final application, like on Android. To make use of this Registry, the gs-collections library must be excluded from the classpath so the factory method will discover that it needs to use the SimpleCachingRegistry instead of the default.
=> Add SimpleCachingRegistry alternative specifically for Android

reactor-core/src/test/java/reactor/io/buffer/BufferTests.java
The unit test for issue #438 modifies important public static state in order to speed up test execution.
It reverts it back to the original values not to affect other unit tests running in the same JVM.
=> #438 improve unit test to leave static state in tact

reactor-stream/src/main/java/reactor/rx/Stream.java, reactor-stream/src/main/java/reactor/rx/action/transformation/GroupByAction.java, reactor-stream/src/test/java/reactor/rx/StreamTests.java
This fix prevents negative hashCodes resulting in negative partition numbers (see https://github.com/reactor/reactor/issues/451)
At the same time, when writing the test, I found it impossible to count the partitions because when the input stream completed, the stream of partitioned streams did not complete. I've made a change to fix this, but not being familiar with this code, it needs review.
=> Issue 451 - Stream.partition(int) creates more partitions than requested

reactor-core/src/main/java/reactor/io/codec/SerializationCodec.java
If client send 2 objects simultaneously server recognizes only one object. It occurs because after SerializationCodec.readType(buffer) position is changed. And we need change position after call buffer.asBytes().
=> Set position after call buffer.asBytes() in SerializationCodec

build.gradle
Spring IO Platform 2.0, which will include Reactor 2.0, will use `com.google.code.findbugs:jsr305:3.0.0`. This PR aligns Reactor's build with the Platform.
=> Upgrade to compile against latest version of JSR 305 annotations

reactor-core/src/main/java/reactor/core/dispatch/RingBufferDispatcher.java, reactor-core/src/test/java/reactor/core/dispatch/RingBufferDispatcherTest.java
The problem which is addressed here is indefinite hanging of StreamCombinationTests which takes place at the very first line (usually) of method after() provided below.
```java
@After
public void after(){
sensorEven.getDispatcher().awaitAndShutdown();
sensorOdd.getDispatcher().awaitAndShutdown();
}
```
Basically, call to .awaitAndShutdown() never returns.
***The root cause:***
BatchEventProcessor from disruptor classes which processes events and blocks on BlockingWaitStrategy could be scheduled onto executor after disruptor.shutdown() method has been called. 
As a result BatchEventProcessor resets its sequenceBarrier alert flag and blocks on a lock condition within BlockingWaitStrategy.
This prevents executor.awaitTermination(timeout, TimeUnit) method to return.
***The corresponding …
=> - hanging of tests due to RingBufferDispatcher.awaitAndShutdown issue

reactor-net/src/main/java/reactor/io/net/http/HttpException.java, reactor-net/src/main/java/reactor/io/net/impl/netty/NettyChannelHandlerBridge.java, reactor-net/src/main/java/reactor/io/net/impl/netty/http/NettyHttpClientHandler.java, reactor-net/src/test/groovy/reactor/io/net/http/HttpResponseStatusCodesHandlingSpec.groovy
Iteration #1 of implementation for handling HTTP response status codes of 400 and 404 on the client side.
=> - implementation for handling HTTP response status codes of 400 and 404

src/docs/asciidoc/streams.adoc
This fixes a few sample issues I ran into in the reference.
=> Fix reference example typos

reactor-bus/src/main/java/reactor/bus/EventBus.java
fixes oversight in https://github.com/reactor/reactor/commit/0b06eb338c657df693e62b1d1eb51a98d5769e78 which requires all users of `getConsumerRegistry()` to cast it to `(Registry<Object, Consumer<? extends Event<?>>>) eventBus.getConsumerRegistry()`
This matches the internally used type.
=> Fixes return type of EventBus.getConsumerRegistry()

build.gradle, reactor-bus/src/main/java/reactor/bus/selector/JsonPathSelector.java
Spring Framework 4.2 and Spring Integration 4.2 are both now building against JsonPath 2.0. This PR aligns Reactor with those projects and implements JsonProvider’s new `unwrap(Object)` method.
=> Upgrade to JsonPath 2.0

reactor-core/src/main/java/reactor/io/buffer/Buffer.java, reactor-core/src/test/groovy/reactor/io/buffer/BufferSpec.groovy
While using TcpServer / TcpClient, I encountered some problems related to Buffer expansion (the Codecs can handle requests containing from few hundreds bytes to several kb).
The fixes were originally made for reactor 1.0.x and are currently used in production. This PR is targeted to master.
Hope this helps.
Guillaume
=> Various Buffer capacity fixes

build.gradle, reactor-core/src/main/java/reactor/io/codec/kryo/KryoPoolCodec.java
KryoCodec is not thread safe and throw ArrayIndexOutOfBoundsException
> Kryo is not thread safe. Each thread should have its own Kryo, Input, and Output instances. Also, the byte[] Input uses may be modified and then returned to its original state during deserialization, so the same byte[] "should not be used concurrently in separate threads.
<...>
you may want to use the KryoPool provided by kryo.
To fix this, I propose KryoPoolCodec.
=> Add thread safe KryoPoolCodec

reactor-net/src/main/java/reactor/io/net/config/CommonSocketOptions.java
The linger value is in second, so 30000 was probably a copy-paste mistake.
I set it to 2, as it seems a reasonable default. The JDK has a negative value, which makes SO_LINGER disabled. Maybe keeping the JDK default could be an even more reasonable default, but I'm not a TCP expert.
The timeout value is reduced to 5 seconds, as it is used as connection establishment timeout, and this seems far enough for a library targeting high throughput. 
Hope this helps,
Guillaume
=> Default value updates for timeout and linger in CommonSocketOptions

reactor-logback/src/main/java/reactor/logback/AsyncAppender.java
The "backlog" parameter getter returns `long` instead of `int`, which makes it impossible to configure the appender in Logback's configuration file (the parser gets confused).
Example:
```
<appender name="ASYNC_FILE" class="reactor.logback.AsyncAppender">
<param name="backlog" value="1024"/>
<appender-ref ref="FILE"/>
</appender>
```
=> Fix inconsistent getter/setter types for backlog parameter

reactor-core/src/main/java/reactor/Publishers.java, reactor-core/src/main/java/reactor/core/publisher/AbstractIteratorSequencer.java, reactor-core/src/main/java/reactor/core/publisher/IterableSequencer.java, reactor-stream/src/main/java/reactor/rx/Streams.java
Previously, only an `Iterable` and not an `Iterator` could be used as a publisher.  As the `Iterable` was used to call `.iterator()` there should have been an equivalent for passing in the `Iterator` directly.  This
change abstracts a common class for the actual iteration while creating separate child classes for initializing the context from an `Iterable` and `Iterator`.  It also adds `from()` and `convert()` behavior
to `Publishers` as well as `from()` behavior to `Streams`.
=> Iterator Publisher

reactor-core/src/main/java/reactor/fn/timer/HashWheelTimer.java, reactor-core/src/main/java/reactor/fn/timer/SettableTimeSupplier.java, reactor-core/src/test/java/reactor/fn/timer/TimerTests.java
Hash Wheel Timer now can get a SettableTimeSupplier,
which can be set for any particular time instance.
=> Implement time travel for HashWheelTimer

reactor-stream/src/test/java/reactor/reactivestreams/tck/AbstractStreamVerification.java, reactor-stream/src/test/java/reactor/reactivestreams/tck/StreamAndProcessorGroupTests.java, reactor-stream/src/test/java/reactor/reactivestreams/tck/StreamAndProcessorTests.java
Some of the generic types cannot be validated by Eclipse or can be
validated, but require configuration. Since there are only a few places
in reactor which use implicit casts, it is easy to make them explicit
and thus allow usage of Eclipse as an IDE for contributors.
=> Use explicit casts to allow development with Eclipse

reactor-core/src/main/java/reactor/core/processor/ProcessorGroup.java
ProcessorGroup#createBarrier creates ProcessorBarriers using the generic
type T. This type is not always desired, e.g. when creating dispatchers
for other types. Casts can easily be avoided and thus problems with the
Eclipse compiler by adding a new generic type to
ProcessorGroup#createBarrier.
This is a follow up to PR 587 [1].
[1] https://github.com/reactor/reactor/pull/587
=> Avoid implicit casting in ProcessorGroup

reactor-stream/src/main/java/reactor/rx/Promise.java
This is a PR containing two separate changes which can be discussed together as they are strongly related.
```
Align Promise#map with Stream#map API
Promise#map accepts a different type of transformations than Stream#map.
This is just a minor API inconsistency. Given the fact that Stream#map
accepts a wider range of transformation functions, this is  a backwards
compatible change.
```
and
```
Use explicit casts in Promise to allow Eclipse usage
Many places in reactor do not require explicit casts since casting is
done implicitly via generic usage. For instance, `Stream#map` accepts
transformation functions of type `? extends V`, but types the
`MapOperator` via generics to `V`.
This is not yet done in `Promise#map` or `Promise#flatMap`. While the
current solution works fine due to implicit …
```
=> Consolidate Promise API and enable Eclipse dev

README.md
=> Groovy String interpolation requires double quotes

reactor-core/src/main/java/reactor/core/timer/Timer.java
the one-shot timer submission uses delay as name of the parameter, not period.
=> Fix typo in Timer Javadoc

CONTRIBUTING.md
This PR adds basic Eclipse project setup instructions. The `CONTRIBUTING.md` looks pretty empty.
=> Document Eclipse project setup

reactor-core/src/main/java/reactor/core/subscriber/SubscriberFactory.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2259 - Null pointers should not be dereferenced
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2259
Please let me know if you have any questions.
Kirill Vlasov
=> Null pointers should not be dereferenced

reactor-core/src/main/java/reactor/Processors.java, reactor-core/src/main/java/reactor/core/error/Exceptions.java, reactor-core/src/main/java/reactor/core/error/SpecificationExceptions.java, reactor-core/src/main/java/reactor/core/publisher/convert/DependencyUtils.java, reactor-core/src/main/java/reactor/core/support/ReactiveStateUtils.java, reactor-core/src/main/java/reactor/core/support/internal/PlatformDependent.java, reactor-logback/src/main/java/reactor/logback/DurableLogUtility.java, reactor-stream/src/main/java/reactor/rx/Promises.java, reactor-stream/src/main/java/reactor/rx/stream/StreamFuture.java, reactor-stream/src/main/java/reactor/rx/stream/StreamRange.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - Utility classes should not have public constructors
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1118
Please let me know if you have any questions.
Kirill Vlasov
=> Utility classes should not have public constructors

reactor-stream/src/main/java/reactor/rx/Stream.java, reactor-stream/src/test/groovy/reactor/rx/StreamsSpec.groovy
Previously there were two tests failing because Groovy could not differentiate between two variants of a given method.  This change updates the tests to explicitly declare the types of the closures used
in these tests to ensure that there would be no ambiguity in method selection.
=> Groovy Ambiguity Fixes

reactor-core/src/main/java/reactor/core/timer/HashWheelTimer.java, reactor-stream/src/main/java/reactor/rx/stream/StreamScan.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1444 - "public static" fields should be constant,
squid:S2387 - Child class members should not shadow parent class members
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1444
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2387
Please let me know if you have any questions.
Kirill Vlasov
=> Code quality fixes

build.gradle
The MANIFEST.MF contains Import-Package declarations for
“reactor.jarjar” which can’t be resolved. So these are being excluded
now and the ClassLoader will satisfy those from the bundle itself.
FIXES #619
=> Fix OSGi import packages for reactor

gradle.properties
I was planning on saying on the site that core is only currently part of `Aluminium-SNAPSHOT`.
=> Aluminium snapshot reflect no new addon, 3.0.7 core released

README.md
Additional minor fixes:
* Update dependency management plugin version
* Fix close tag in Maven repositories block
Signed-off-by: Parker Mauney <parkermauney@gmail.com>
=> Mention Gradle 5.0+ native BOM support in README

README.md
Curent link in README.md doesn't work
=> [Obvious Fix] Update README.md : fix documentation link

build.gradle, settings.gradle
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were fixed, but the https status was not OK. However, the https status was the same as the http request or http redirected to an https URL, so they were migrated. Your review is recommended.
* http://repo.spring.io/libs-snapshot (502) migrated to:  
https://repo.spring.io/libs-snapshot ([https](https://repo.spring.io/libs-snapshot) result 502).
* http://repo.spring.io/milestone (502) migrated to:  
https://repo.spring.io/milestone ([https](https://repo.spring.io/milestone) result 502).
* http://repo.spring.io/release (502) migrated to:  
https://repo.spring.io/release …
=> URL Cleanup

build.gradle, gradle.properties, gradle/releaser.gradle
This is only activated when passing a non-false `-PreleaserDryRun` to Gradle.
=> Conditionnally add mavenLocal when releaser script is applied

README.md, gradle.properties
This commit switches the effort on master from Dysprosium to Europium.
It also introduces a new versioning scheme, using -SNAPSHOT
instead of .BUILD-SNAPSHOT as the qualifier for snapshots.
The whole scheme is detailed in the reference documentation of core,
as well as in the README here.
Adaptations are made to the build script to accommodate it.
See #683
=> [build] Start 2020.0 Europium, introduce new versioning scheme

.github/workflows/publish.yml, build.gradle, gradle/releaser.gradle
This commit changes the release process to be based on GitHub Actions.
No CI is currently running for the BOM.
We define helper tasks and methods in the setup.gradle file to help
interpret the version number. The trigger is pushing a commit to an
active maintenance branch.
The new workflow uses GitHub Environments to manage access to secrets,
especially in the case of milestones and releases as it introduces
signing of artifacts in these cases. It is split into 4 jobs, 3 of
which are conditional and depend on a GitHub Environment.
Notably:
- Add a function to qualify a BOM version as one of RELEASE,
MILESTONE, SNAPSHOT or BAD. Recognizes `Dysprosium` as old scheme.
- Add a GitHub Actions oriented task, `qualifyVersionGha`, which
produces gha step output for the current project version. …
=> GitHub Actions Release Process

README.md, build.gradle, gradle/releaser.gradle, settings.gradle
- copyright header to VMware instead of Pivotal
- in copyright headers, have date range end on 2021
- polish copyright header: url indentation, blank line after license
- fix pom: update developer list (and emails), update organization
- remove remaining occurrences of Pivotal (eg. in README)
See reactor/reactor#682.
=> [chores] Copyright switch Pivotal to VMware, polish headers

.github/workflows/publish.yml
Note the `2020.0.x` is a literal match and not a glob pattern (`.` is
a literal, unlike in regular expressions).
=> Start of branch 2020.0.x, adapt CI and build

gradle.properties
This commit represents the first BOM of 2022.0 snapshots.
Most notably, reactor-kafka and reactor-rabbitmq have been removed
from the BOM as these projects will either have their own out-of-band
release cycle in 2022, or further than that they'll move out of the
reactor org.
=> Start 2022.0 snapshots BOM, remove kafka/rabbitmq from BOM

build.gradle, gradle.properties
This PR extracts the version number of Reactive-Streams dependency into the
gradle.properties file.
Since there was a recent release of the library following a relicensing and
including TCK improvements, the version is also upgraded to 1.0.4.
This is in alignment with the dependency declared in Reactor-Core itself.
=> Extract Reactive-Streams version and upgrade to 1.0.4

build.gradle, gradle.properties
When discussing the future of Reactor-Kafka, it was requested that the project be reintegrated into the BOM of `2022.0`.
In order to limit the maintenance and release effort for the Reactor team, we'll attempt to use a single common version for both release trains `2020.0` and upcoming `2022.0`.
=> Reintegrate Reactor-Kafka in BOM, using 1.3.x common line

README.md, build.gradle, gradle.properties
https://spring.io/blog/2025/05/20/reactor-kafka-discontinued
=> Remove reactor-kafka from BOM and update README.md
